# Generated by Django 5.2.7 on 2025-10-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_registro',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
