# Generated by Django 5.2.7 on 2025-10-28 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_examen_muestra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultado',
            options={'ordering': ['orden_examen', 'parametro']},
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='creado_en',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='actualizado_en',
            new_name='modificado',
        ),
        migrations.AddField(
            model_name='resultado',
            name='acreditado',
            field=models.BooleanField(default=True, verbose_name='Acreditado'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='es_calculado',
            field=models.BooleanField(default=False, verbose_name='Es calculado'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='fuera_de_rango',
            field=models.BooleanField(default=False, verbose_name='Fuera de rango'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='metodo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Método'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='parametro',
            field=models.CharField(max_length=120, verbose_name='Parámetro'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valores de referencia'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='validado',
            field=models.BooleanField(default=False, verbose_name='Validado'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='valor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor'),
        ),
    ]
