# Generated by Django 5.2.7 on 2025-10-28 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_alter_resultado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del parámetro')),
                ('unidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valores de referencia')),
                ('metodo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Método analítico')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones automáticas')),
                ('acreditado', models.BooleanField(default=True, verbose_name='Acreditado')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='laboratorio.examen')),
            ],
            options={
                'verbose_name': 'Parámetro de examen',
                'verbose_name_plural': 'Parámetros de examen',
                'ordering': ['examen', 'nombre'],
            },
        ),
    ]
