# Generated by Django 5.2.7 on 2025-10-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_examenparametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
