# Generated by Django 5.2.7 on 2025-10-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_resultado_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('En validación', 'En validación'), ('Validado', 'Validado')], default='Pendiente', max_length=20),
        ),
    ]
