# Generated by Django 4.2.26 on 2025-12-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_alter_orden_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultado',
            options={},
        ),
        migrations.AddField(
            model_name='resultado',
            name='orden_equipo',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
