# Generated by Django 5.2.11 on 2026-02-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0008_alter_resultado_options_resultado_orden_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='pdf_ruta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta del PDF generado'),
        ),
    ]
