# Generated by Django 5.2.11 on 2026-02-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_add_pdf_ruta_to_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateField(blank=True, help_text='Fecha de registro del paciente', null=True),
        ),
    ]
