# Generated by Django 5.2.11 on 2026-03-11 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0010_paciente_fecha_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proforma', models.CharField(max_length=20, unique=True)),
                ('medico', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('mostrar_precios', models.BooleanField(default=True, verbose_name='Mostrar precios unitarios en PDF')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_creado_por', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.examen')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='laboratorio.proforma')),
            ],
        ),
    ]
