# Generated by Django 5.2.11 on 2026-03-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0011_proforma_proformaexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
