# Generated by Django 4.2.26 on 2025-11-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(default='Mi Laboratorio', max_length=180)),
                ('ruc', models.CharField(blank=True, default='', max_length=20)),
                ('direccion', models.CharField(blank=True, default='', max_length=250)),
                ('telefono', models.CharField(blank=True, default='', max_length=120)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('markup_por_defecto', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parámetro general',
                'verbose_name_plural': 'Parámetros generales',
            },
        ),
    ]
