# Generated by Django 4.2.26 on 2025-11-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_alter_orden_estado'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fabricante', models.CharField(blank=True, default='', max_length=120)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_integracion', models.CharField(choices=[('MANUAL', 'Sin integración (solo manual)'), ('ASTM', 'ASTM (Puerto serie)'), ('HL7', 'HL7 (TCP/IP)'), ('CSV', 'Archivo CSV'), ('TXT', 'Archivo TXT')], default='MANUAL', max_length=10)),
                ('host', models.CharField(blank=True, default='', help_text='IP o nombre de host (solo para HL7/ASTM TCP).', max_length=120)),
                ('puerto', models.CharField(blank=True, default='', help_text='Puerto TCP o COM (según el tipo de integración).', max_length=20)),
                ('ruta_archivos', models.CharField(blank=True, default='', help_text='Ruta de carpeta para archivos CSV/TXT.', max_length=255)),
                ('prefijo_archivo', models.CharField(blank=True, default='', help_text='Prefijo de nombre de archivo que el LIS debe leer (opcional).', max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='EquipoMapeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipo', models.CharField(help_text='Código que envía el equipo en el mensaje/archivo.', max_length=80)),
                ('parametro', models.CharField(blank=True, default='', help_text='Parámetro interno (ej. GLUCOSA, HGB, PCR-US).', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos', to='configuracion.equipo')),
                ('examen', models.ForeignKey(blank=True, help_text='Examen interno al que se asignará.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorio.examen')),
            ],
            options={
                'verbose_name': 'Mapeo de equipo',
                'verbose_name_plural': 'Mapeos de equipos',
                'unique_together': {('equipo', 'codigo_equipo')},
            },
        ),
    ]
