# Generated by Django 4.2.26 on 2025-11-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_equipo_equipomapeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HL7Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('ip_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje_raw', models.TextField()),
                ('msh', models.TextField(blank=True, null=True)),
                ('pid', models.TextField(blank=True, null=True)),
                ('obr', models.TextField(blank=True, null=True)),
                ('obx', models.TextField(blank=True, null=True)),
                ('sample_id', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_codes', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
            ],
        ),
    ]
