# Generated by Django 4.2.26 on 2025-12-01 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_hl7mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='HL7Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='lis_imagenes/%Y/%m/%d/')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('formato', models.CharField(default='bmp', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='configuracion.hl7mensaje')),
            ],
        ),
    ]
