# Generated by Django 5.2.11 on 2026-03-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_hl7imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='hl7mensaje',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta del equipo'), ('resultado', 'Resultado enviado por equipo'), ('respuesta', 'Respuesta del sistema')], default='resultado', max_length=20),
        ),
    ]
